// <auto-generated />
using HackathonEarthquake.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackathonEarthquake.Repository.Migrations
{
    [DbContext(typeof(EarthquakeDbContext))]
    [Migration("20240519055249_InıtialDatabase")]
    partial class InıtialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İstanbul"
                        });
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Eyüp"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Ümraniye"
                        });
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.MeetingPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedUsed")
                        .HasColumnType("int");

                    b.Property<string>("OpenAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalNumberOfBed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MeetingPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            DistrictId = 1,
                            Name = "Çırçır Toplanma Alanı",
                            NeighbourhoodId = 1,
                            NumberOfBedUsed = 100,
                            OpenAddress = "Çırçır Mahallesi Funda Sokak Eyüp/İstanbul",
                            TotalNumberOfBed = 150
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            DistrictId = 1,
                            Name = "Karadolap Toplanma Alanı",
                            NeighbourhoodId = 1,
                            NumberOfBedUsed = 75,
                            OpenAddress = "Karadolap Mahallesi Bilmiyom Sokak Eyüp/İstanbul",
                            TotalNumberOfBed = 175
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            DistrictId = 2,
                            Name = "Çakmak Toplanma Alanı",
                            NeighbourhoodId = 2,
                            NumberOfBedUsed = 55,
                            OpenAddress = "Çakmak Mahallesi Yenigün Sokak Ümraniye/İstanbul",
                            TotalNumberOfBed = 75
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            DistrictId = 2,
                            Name = "Çamlık Toplanma Alanı",
                            NeighbourhoodId = 2,
                            NumberOfBedUsed = 95,
                            OpenAddress = "Çamlık Mahallesi Bilmiyomiki Sokak Ümraniye/İstanbul",
                            TotalNumberOfBed = 125
                        });
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.Neighbourhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Neighbourhoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 1,
                            Name = "Çırçır"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 1,
                            Name = "Karadolap"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 2,
                            Name = "Çakmak"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 2,
                            Name = "Çamlık"
                        });
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.District", b =>
                {
                    b.HasOne("HackathonEarthquake.Core.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.Neighbourhood", b =>
                {
                    b.HasOne("HackathonEarthquake.Core.Entities.District", "District")
                        .WithMany("Neighbourhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("HackathonEarthquake.Core.Entities.District", b =>
                {
                    b.Navigation("Neighbourhoods");
                });
#pragma warning restore 612, 618
        }
    }
}
